matrix:
  include:
    - language: node_js
      node_js:
        - "8.9.4"
      install:
        - npm install --global yarn
      before_script:
        - yarn install
      script:
        - npm run webpack
    - language: python
      python:
        - 2.7
      install:
        - pip install tox
      script:
        - tox -e py27
    - language: python
      python:
        - 3.6
      install:
        - pip install tox
      script:
        - tox -e py36
    - language: pyhton
      python:
        - 3.6
      install:
        - pip install tox
      script:
        - tox -e flake8
